### ISSUE TITLE
Problem with your plugin and TabrisJs

### ISSUE THREAD

**Issue by ishigo1987** [Kuldeep-Kumar-Sharma/camerakitcordova-plugin#2]
Hello i'm trying to use your plugin but i have some problem during the compilation time
i'm working with the TabrisJs framework and i've this error with the build

Failed to install 'com.kuldeep': CordovaError: Uh oh!
"/home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/android/app/src/main/res/values/strings.xml" already exists!
    at copyNewFile (/home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/android/cordova/lib/pluginHandlers.js:236:45)
    at install (/home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/android/cordova/lib/pluginHandlers.js:35:17)
    at ActionStack.process (/home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)

Basicaly the problem came to the fact that your plugin is attempting to overwrite strings.xml instead of appending to it
can you fix that please
you have a really nice plugin and i want to use it

**Comment by kuldeepKumar94** [comment]
yeah, I can do, it all together you can also fix it by copying, the content again and over, But I would be updating it soon, Thanks for the update

**Comment by ishigo1987** [comment]
Thank you to you.
I'm waiting for the update

**Comment by ishigo1987** [comment]
Hello how are you?any news?

**Comment by kuldeepKumar94** [comment]
Yup, I am updating, due to Cordova version update, I bundle up the changes and update you

**Comment by ishigo1987** [comment]
ok thank you i'm waiting for your update

**Comment by kuldeepKumar94** [comment]
I have updated the plugin and you can check, whether it works fine for, I open to new suggestions, and If you want some other plugin to be created, please update me, I can work on it.

**Comment by ishigo1987** [comment]
Ok thank you very much i will let you know next week

**Comment by kuldeepKumar94** [comment]
hey, hope you were able to use it, now, closing the issue for now.

**Comment by ishigo1987** [comment]
Ok no problem thank you again
